# 1. Import Libraries

In [585]:
import pandas as pd
import numpy as np

In [586]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# 2. Import Dataset

In [587]:
df = pd.read_csv('datasets/cleaned_dataset.csv')
df.head()

Date  HomeTeam    AwayTeam  FTHG  FTAG    HS   AS   HST  AST  B365H  \
0  2012-08-18   arsenal  sunderland   0.0   0.0  14.0  3.0   4.0  2.0   1.40   
1  2012-09-01   swansea  sunderland   2.0   2.0  14.0  4.0  10.0  3.0   2.20   
2  2012-09-22  west-ham  sunderland   1.0   1.0  20.0  4.0  11.0  2.0   2.10   
3  2012-10-06      city  sunderland   3.0   0.0  26.0  8.0  16.0  6.0   1.29   
4  2012-10-27     stoke  sunderland   0.0   0.0  11.0  6.0   6.0  3.0   1.95   

   B365D  B365A Result  HDays  ADays  HASL5M  HASTL5M  HGDL5M  HGDL5HM  \
0    4.5    8.5      D      0      0     NaN      NaN     NaN      NaN   
1    3.3    3.4      D      0      0     NaN      NaN     NaN      NaN   
2    3.3    3.6      D      0      0     NaN      NaN     NaN      NaN   
3    5.5   11.0      W      1      1    16.0     10.0     3.0      NaN   
4    3.3    4.2      D      0      0     8.0      4.6    -1.0      NaN   

   HAPL5M  HAPL5HM  HWinStreak  AASL5M  AASTL5M  AGDL5M  AGDL5AM  AAPL5M  \
0     NaN      NaN         NaN     NaN      NaN     NaN      NaN     NaN   
1     NaN      NaN         2.0     NaN      NaN     NaN      NaN     NaN   
2     NaN      NaN         0.0     NaN      NaN     NaN      NaN     NaN   
3     1.8      NaN         1.0     5.6      3.4     1.0      NaN     1.4   
4     1.0      NaN         0.0     9.0      4.8    -2.0      NaN     1.2   

   AAPL5AM  AWinStreak  HDef  HMid  HAtt  ADef  AMid  AAtt  
0      NaN         NaN    80    82    84    74    75    78  
1      NaN         0.0    73    73    73    74    75    77  
2      NaN         0.0    71    73    75    74    75    77  
3      NaN         1.0    81    83    85    74    75    77  
4      NaN         0.0    75    76    75    74    75    77

In [588]:
# df['HRating'] = (df['HDef'] + df['HMid'] + df['HAtt'] ) / 3
# df['ARating'] = (df['ADef'] + df['AMid'] + df['AAtt'] ) / 3
# df.head()

In [589]:
df = df[['HDays', 'ADays',
         'HASL5M', 'HASTL5M',
         'HGDL5M', 'HGDL5HM', 'HAPL5M', 'HAPL5HM',
         'AASL5M', 'AASTL5M',
         'AGDL5M', 'AGDL5AM', 'AAPL5M','AAPL5AM', 
         'HDef', 'HMid', 'HAtt', 
         'ADef', 'AMid', 'AAtt',
         'B365H', 'B365D', 'B365A',
         'Result'
        ]]
df.head()

HDays  ADays  HASL5M  HGDL5M  HGDL5HM  HAPL5M  HAPL5HM  AASL5M  AGDL5M  \
0      0      0     NaN     NaN      NaN     NaN      NaN     NaN     NaN   
1      0      0     NaN     NaN      NaN     NaN      NaN     NaN     NaN   
2      0      0     NaN     NaN      NaN     NaN      NaN     NaN     NaN   
3      1      1    16.0     3.0      NaN     1.8      NaN     5.6     1.0   
4      0      0     8.0    -1.0      NaN     1.0      NaN     9.0    -2.0   

   AGDL5AM  AAPL5M  AAPL5AM  HDef  HMid  HAtt  ADef  AMid  AAtt  B365H  B365D  \
0      NaN     NaN      NaN    80    82    84    74    75    78   1.40    4.5   
1      NaN     NaN      NaN    73    73    73    74    75    77   2.20    3.3   
2      NaN     NaN      NaN    71    73    75    74    75    77   2.10    3.3   
3      NaN     1.4      NaN    81    83    85    74    75    77   1.29    5.5   
4      NaN     1.2      NaN    75    76    75    74    75    77   1.95    3.3   

   B365A Result  
0    8.5      D  
1    3.4      D  
2    3.6      D  
3   11.0      W  
4    4.2      D

In [590]:
df = df.dropna(axis=0).reset_index(drop=True)
df.head()

HDays  ADays  HASL5M  HGDL5M  HGDL5HM  HAPL5M  HAPL5HM  AASL5M  AGDL5M  \
0      0      0    12.8     1.0      8.0     1.4      2.0     9.4    -5.0   
1      1      1     9.8     2.0      0.0     1.8      2.0    12.2    -2.0   
2      0      0    13.6     4.0      5.0     2.4      2.4    15.6    -2.0   
3      0      0    14.4     4.0      2.0     2.0      1.6    14.4    -2.0   
4      1      1    18.4     4.0      6.0     1.8      2.0    12.0     2.0   

   AGDL5AM  AAPL5M  AAPL5AM  HDef  HMid  HAtt  ADef  AMid  AAtt  B365H  B365D  \
0     -4.0     0.4      0.6    75    77    78    74    75    77   1.67   3.75   
1     -2.0     0.8      1.0    73    72    72    74    75    77   2.10   3.30   
2     -3.0     0.8      0.8    83    82    86    74    75    77   1.20   6.50   
3     -2.0     0.8      0.8    72    70    73    74    75    77   2.00   3.50   
4     -1.0     1.8      1.2    79    80    79    74    75    77   1.40   4.50   

   B365A Result  
0   5.25      L  
1   3.60      W  
2  15.00      W  
3   3.75      L  
4   8.50      W

In [591]:
df.shape

(3553, 22)

# 2. Model Building

## 2.1 Descision Tree Classifier

Highest Accuracy: 44.83 %

In [592]:
X = df.iloc[:, :-1].values
# X = df.iloc[:, :16].values
y = df.iloc[:, -1].values

In [593]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [594]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [595]:
# from sklearn.decomposition import PCA
# pca = PCA(n_components = 2)
# X_train = pca.fit_transform(X_train)
# X_test = pca.transform(X_test)

In [596]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 2)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

In [597]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [598]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['W' 'W']
 ['W' 'W']
 ['L' 'W']
 ...
 ['W' 'W']
 ['D' 'W']
 ['D' 'W']]


In [599]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 49  51  67]
 [ 54  83  79]
 [ 78  74 176]]


0.43319268635724334

In [600]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 5)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))

Accuracy: 45.11 %


## 2.2 SVM Classifier

Highest Accuracy: 54.99 %

In [601]:
X = df.iloc[:, :-1].values
# X = df.iloc[:, :16].values
y = df.iloc[:, -1].values

In [602]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [603]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [604]:
# from sklearn.decomposition import PCA
# pca = PCA(n_components = 2)
# X_train = pca.fit_transform(X_train)
# X_test = pca.transform(X_test)

In [605]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 2)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

In [606]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [607]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['W' 'W']
 ['W' 'W']
 ['L' 'W']
 ...
 ['W' 'W']
 ['W' 'W']
 ['W' 'W']]


In [608]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  4  57 139]
 [  7 138 128]
 [  9  70 337]]


0.5388076490438695

In [609]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 5)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))

Accuracy: 54.88 %


## 2.3 Naive Bayes Classifier

Highest Accuracy: 55.63

In [610]:
X = df.iloc[:, :-1].values
# X = df.iloc[:, :16].values
y = df.iloc[:, -1].values

In [611]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [612]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [613]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 2)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

In [614]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [615]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['W' 'W']
 ['W' 'W']
 ['D' 'W']
 ...
 ['W' 'W']
 ['W' 'W']
 ['W' 'W']]


In [616]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 32  43 125]
 [ 44 116 113]
 [ 51  47 318]]


0.5241844769403825

In [617]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 5)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))

Accuracy: 55.52 %


## 2.4 KNN Classifier

Highest Accuracy: 47.71 %

In [618]:
X = df.iloc[:, :-1].values
# X = df.iloc[:, :16].values
y = df.iloc[:, -1].values

In [619]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [620]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [621]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 2)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

In [622]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [623]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['W' 'W']
 ['W' 'W']
 ['L' 'W']
 ...
 ['W' 'W']
 ['W' 'W']
 ['D' 'W']]


In [624]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 62  60  78]
 [ 64 142  67]
 [ 95 104 217]]


0.4735658042744657

In [625]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 5)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))

Accuracy: 46.81 %
