# 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# 2. Import Dataset

In [3]:
df = pd.read_csv('datasets/finalized_dataset.csv')
df.head()

Date      HomeTeam   AwayTeam  FTHG  FTAG  HS  AS  HST  AST  HF  AF  \
0  2017-08-11       arsenal  leicester     4     3  27   6   10    3   9  12   
1  2017-08-26        united  leicester     2     0  22  11    7    4   8   7   
2  2017-09-16  huddersfield  leicester     1     1  15  10    3    1   6   6   
3  2017-09-30   bournemouth  leicester     0     0  19   8    4    1   6  10   
4  2017-10-21       swansea  leicester     1     2  19  11    4    6   6   9   

   HC  AC  HY  AY  HR  AR  B365H  B365D  B365A Result  HxG  AxG  HPoss  \
0   9   4   0   1   0   0   1.53   4.50   6.50      W  2.5  1.5   68.0   
1   9   3   1   2   0   0   1.33   5.50  11.00      W  2.8  0.9   69.0   
2   8   4   1   1   0   0   3.50   3.40   2.25      D  0.7  1.3   59.0   
3   7   5   1   0   0   0   2.80   3.25   2.50      D  1.4  0.6   61.0   
4   7   6   0   1   0   0   2.79   3.25   2.75      L  0.8  1.9   56.0   

   HDaysLastPlayed  ADaysLastPlayed  HxGD in Last 5 Matches  \
0                5               10                     NaN   
1                7                4                     NaN   
2                5                7                     NaN   
3                7                7                    -6.0   
4                7                5                    -1.0   

   HxGD in Last 5 Home Matches  HAvgPts in Last 5 Matches  \
0                          NaN                        NaN   
1                          NaN                        NaN   
2                          NaN                        NaN   
3                          NaN                        0.6   
4                          NaN                        0.8   

   HAvgPts in Last 5 Home Matches  AxGD in Last 5 Matches  \
0                             NaN                     NaN   
1                             NaN                     NaN   
2                             NaN                     NaN   
3                             NaN                    -2.0   
4                             NaN                    -2.0   

   AxGD in Last 5 Away Matches  AAvgPts in Last 5 Matches  \
0                          NaN                        NaN   
1                          NaN                        NaN   
2                          NaN                        NaN   
3                          NaN                        0.8   
4                          NaN                        0.6   

   AAvgPts in Last 5 Away Matches  HDef  HMid  HAtt  ADef  AMid  AAtt  
0                             NaN    82    83    81    76    78    79  
1                             NaN    82    84    84    76    78    79  
2                             NaN    71    70    70    76    78    79  
3                             NaN    75    74    76    76    78    80  
4                             NaN    75    77    76    76    78    79

In [4]:
df.drop(df.iloc[:, :17], inplace=True, axis=1)
df.drop(['HxG', 'AxG', 'HPoss'], axis=1, inplace=True)
df.head()

B365H  B365D  B365A Result  HDaysLastPlayed  ADaysLastPlayed  \
0   1.53   4.50   6.50      W                5               10   
1   1.33   5.50  11.00      W                7                4   
2   3.50   3.40   2.25      D                5                7   
3   2.80   3.25   2.50      D                7                7   
4   2.79   3.25   2.75      L                7                5   

   HxGD in Last 5 Matches  HxGD in Last 5 Home Matches  \
0                     NaN                          NaN   
1                     NaN                          NaN   
2                     NaN                          NaN   
3                    -6.0                          NaN   
4                    -1.0                          NaN   

   HAvgPts in Last 5 Matches  HAvgPts in Last 5 Home Matches  \
0                        NaN                             NaN   
1                        NaN                             NaN   
2                        NaN                             NaN   
3                        0.6                             NaN   
4                        0.8                             NaN   

   AxGD in Last 5 Matches  AxGD in Last 5 Away Matches  \
0                     NaN                          NaN   
1                     NaN                          NaN   
2                     NaN                          NaN   
3                    -2.0                          NaN   
4                    -2.0                          NaN   

   AAvgPts in Last 5 Matches  AAvgPts in Last 5 Away Matches  HDef  HMid  \
0                        NaN                             NaN    82    83   
1                        NaN                             NaN    82    84   
2                        NaN                             NaN    71    70   
3                        0.8                             NaN    75    74   
4                        0.6                             NaN    75    77   

   HAtt  ADef  AMid  AAtt  
0    81    76    78    79  
1    84    76    78    79  
2    70    76    78    79  
3    76    76    78    80  
4    76    76    78    79

In [5]:
df.columns

Index(['B365H', 'B365D', 'B365A', 'Result', 'HDaysLastPlayed',
       'ADaysLastPlayed', 'HxGD in Last 5 Matches',
       'HxGD in Last 5 Home Matches', 'HAvgPts in Last 5 Matches',
       'HAvgPts in Last 5 Home Matches', 'AxGD in Last 5 Matches',
       'AxGD in Last 5 Away Matches', 'AAvgPts in Last 5 Matches',
       'AAvgPts in Last 5 Away Matches', 'HDef', 'HMid', 'HAtt', 'ADef',
       'AMid', 'AAtt'],
      dtype='object')

In [6]:
df = df[['HDaysLastPlayed', 'ADaysLastPlayed', 
         'HxGD in Last 5 Matches', 'HxGD in Last 5 Home Matches', 'HAvgPts in Last 5 Matches', 'HAvgPts in Last 5 Home Matches', 
         'AxGD in Last 5 Matches', 'AxGD in Last 5 Away Matches', 'AAvgPts in Last 5 Matches','AAvgPts in Last 5 Away Matches', 
         'HDef', 'HMid', 'HAtt', 'ADef', 'AMid', 'AAtt',
         'B365H', 'B365D', 'B365A',
         'Result'
        ]]
df.head()

HDaysLastPlayed  ADaysLastPlayed  HxGD in Last 5 Matches  \
0                5               10                     NaN   
1                7                4                     NaN   
2                5                7                     NaN   
3                7                7                    -6.0   
4                7                5                    -1.0   

   HxGD in Last 5 Home Matches  HAvgPts in Last 5 Matches  \
0                          NaN                        NaN   
1                          NaN                        NaN   
2                          NaN                        NaN   
3                          NaN                        0.6   
4                          NaN                        0.8   

   HAvgPts in Last 5 Home Matches  AxGD in Last 5 Matches  \
0                             NaN                     NaN   
1                             NaN                     NaN   
2                             NaN                     NaN   
3                             NaN                    -2.0   
4                             NaN                    -2.0   

   AxGD in Last 5 Away Matches  AAvgPts in Last 5 Matches  \
0                          NaN                        NaN   
1                          NaN                        NaN   
2                          NaN                        NaN   
3                          NaN                        0.8   
4                          NaN                        0.6   

   AAvgPts in Last 5 Away Matches  HDef  HMid  HAtt  ADef  AMid  AAtt  B365H  \
0                             NaN    82    83    81    76    78    79   1.53   
1                             NaN    82    84    84    76    78    79   1.33   
2                             NaN    71    70    70    76    78    79   3.50   
3                             NaN    75    74    76    76    78    80   2.80   
4                             NaN    75    77    76    76    78    79   2.79   

   B365D  B365A Result  
0   4.50   6.50      W  
1   5.50  11.00      W  
2   3.40   2.25      D  
3   3.25   2.50      D  
4   3.25   2.75      L

In [7]:
df = df.dropna(axis=0).reset_index(drop=True)
df.head()

HDaysLastPlayed  ADaysLastPlayed  HxGD in Last 5 Matches  \
0                7                6                    -8.0   
1                5                6                    -8.0   
2                7                7                    -9.0   
3                3                4                    -1.0   
4                3                3                    -6.0   

   HxGD in Last 5 Home Matches  HAvgPts in Last 5 Matches  \
0                         -3.0                        1.2   
1                         -4.0                        0.4   
2                         -2.0                        0.2   
3                          3.0                        1.0   
4                         -4.0                        0.2   

   HAvgPts in Last 5 Home Matches  AxGD in Last 5 Matches  \
0                             1.4                     2.0   
1                             1.2                     1.0   
2                             1.4                     0.0   
3                             1.6                     1.0   
4                             0.8                     2.0   

   AxGD in Last 5 Away Matches  AAvgPts in Last 5 Matches  \
0                         -2.0                        1.6   
1                         -1.0                        1.6   
2                          1.0                        1.6   
3                          2.0                        2.0   
4                          5.0                        2.0   

   AAvgPts in Last 5 Away Matches  HDef  HMid  HAtt  ADef  AMid  AAtt  B365H  \
0                             1.0    77    76    78    76    80    79   2.70   
1                             1.2    78    78    79    76    78    79   2.70   
2                             1.4    75    74    74    76    80    78   2.62   
3                             1.8    79    78    78    76    80    78   2.10   
4                             2.2    75    78    76    76    79    79   2.54   

   B365D  B365A Result  
0   3.29   2.87      D  
1   3.39   2.75      D  
2   3.29   2.89      L  
3   3.39   3.89      L  
4   3.50   2.87      W

# 2. Model Building

## 2.1 Descision Tree Classifier

In [8]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [13]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['W' 'D']
 ['W' 'W']
 ['L' 'L']
 ...
 ['L' 'L']
 ['D' 'W']
 ['W' 'W']]


In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 37  36  43]
 [ 50  74  55]
 [ 63  47 111]]


0.43023255813953487

## 2.2 SVM Classifier

In [8]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [12]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['L' 'D']
 ['W' 'W']
 ['L' 'L']
 ['W' 'D']
 ['L' 'L']
 ['W' 'L']
 ['W' 'W']
 ['W' 'W']
 ['W' 'W']
 ['L' 'L']
 ['W' 'D']
 ['W' 'W']
 ['L' 'D']
 ['W' 'W']
 ['W' 'L']
 ['W' 'D']
 ['W' 'W']
 ['W' 'W']
 ['W' 'W']
 ['W' 'L']
 ['W' 'W']
 ['W' 'L']
 ['W' 'W']
 ['W' 'W']
 ['L' 'W']
 ['W' 'W']
 ['W' 'L']
 ['L' 'L']
 ['W' 'L']
 ['W' 'W']
 ['L' 'D']
 ['L' 'D']
 ['W' 'D']
 ['W' 'L']
 ['W' 'W']
 ['W' 'D']
 ['W' 'D']
 ['L' 'L']
 ['W' 'W']
 ['W' 'W']
 ['W' 'L']
 ['W' 'D']
 ['W' 'L']
 ['W' 'L']
 ['W' 'W']
 ['L' 'L']
 ['W' 'L']
 ['W' 'L']
 ['W' 'L']
 ['W' 'W']
 ['W' 'W']
 ['W' 'W']
 ['W' 'W']
 ['W' 'W']
 ['W' 'W']
 ['L' 'L']
 ['W' 'W']
 ['W' 'L']
 ['L' 'L']
 ['L' 'L']
 ['W' 'W']
 ['W' 'L']
 ['W' 'W']
 ['W' 'L']
 ['L' 'W']
 ['W' 'L']
 ['W' 'W']
 ['W' 'W']
 ['W' 'W']
 ['W' 'W']
 ['W' 'L']
 ['W' 'L']
 ['W' 'W']
 ['W' 'W']
 ['W' 'D']
 ['W' 'D']
 ['L' 'W']
 ['W' 'D']
 ['L' 'L']
 ['W' 'W']
 ['W' 'W']
 ['L' 'W']
 ['W' 'D']
 ['W' 'D']
 ['W' 'D']
 ['L' 'L']
 ['W' 'L']
 ['W' 'W']
 ['W' 'W']
 ['W' 'L']
 ['W' 'D']

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  0  14  89]
 [  0  56  96]
 [  0  22 153]]


0.48604651162790696