# 1. Import Libraries

In [20]:
import pandas as pd
import numpy as np

In [21]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# 2. Import Dataset

In [22]:
df = pd.read_csv('datasets/cleaned_dataset.csv')
df.head()

Date  HomeTeam    AwayTeam  FTHG  FTAG  B365H  B365D  B365A Result  \
0  2012-08-18   arsenal  sunderland   0.0   0.0   1.40    4.5    8.5      D   
1  2012-09-01   swansea  sunderland   2.0   2.0   2.20    3.3    3.4      D   
2  2012-09-22  west-ham  sunderland   1.0   1.0   2.10    3.3    3.6      D   
3  2012-10-06      city  sunderland   3.0   0.0   1.29    5.5   11.0      W   
4  2012-10-27     stoke  sunderland   0.0   0.0   1.95    3.3    4.2      D   

   HDays  ADays  HGDL5M  HGDL5HM  HAPL5M  HAPL5HM  HWinStreak  AGDL5M  \
0      0      0     NaN      NaN     NaN      NaN         NaN     NaN   
1      0      0     NaN      NaN     NaN      NaN         2.0     NaN   
2      0      0     NaN      NaN     NaN      NaN         0.0     NaN   
3      1      1     3.0      NaN     1.8      NaN         1.0     1.0   
4      0      0    -1.0      NaN     1.0      NaN         0.0    -2.0   

   AGDL5AM  AAPL5M  AAPL5AM  AWinStreak  HDef  HMid  HAtt  ADef  AMid  AAtt  
0      NaN     NaN      NaN         NaN    80    82    84    74    75    78  
1      NaN     NaN      NaN         0.0    73    73    73    74    75    77  
2      NaN     NaN      NaN         0.0    71    73    75    74    75    77  
3      NaN     1.4      NaN         1.0    81    83    85    74    75    77  
4      NaN     1.2      NaN         0.0    75    76    75    74    75    77

In [23]:
# df['HRating'] = (df['HDef'] + df['HMid'] + df['HAtt'] ) / 3
# df['ARating'] = (df['ADef'] + df['AMid'] + df['AAtt'] ) / 3
# df.head()

In [24]:
df = df[['HDays', 'ADays', 
         'HGDL5M', 'HGDL5HM', 'HAPL5M', 'HAPL5HM', 
         'AGDL5M', 'AGDL5AM', 'AAPL5M','AAPL5AM', 
         'HDef', 'HMid', 'HAtt', 
         'ADef', 'AMid', 'AAtt',
         'B365H', 'B365D', 'B365A',
         'Result'
        ]]
df.head()

HDays  ADays  HGDL5M  HGDL5HM  HAPL5M  HAPL5HM  AGDL5M  AGDL5AM  AAPL5M  \
0      0      0     NaN      NaN     NaN      NaN     NaN      NaN     NaN   
1      0      0     NaN      NaN     NaN      NaN     NaN      NaN     NaN   
2      0      0     NaN      NaN     NaN      NaN     NaN      NaN     NaN   
3      1      1     3.0      NaN     1.8      NaN     1.0      NaN     1.4   
4      0      0    -1.0      NaN     1.0      NaN    -2.0      NaN     1.2   

   AAPL5AM  HDef  HMid  HAtt  ADef  AMid  AAtt  B365H  B365D  B365A Result  
0      NaN    80    82    84    74    75    78   1.40    4.5    8.5      D  
1      NaN    73    73    73    74    75    77   2.20    3.3    3.4      D  
2      NaN    71    73    75    74    75    77   2.10    3.3    3.6      D  
3      NaN    81    83    85    74    75    77   1.29    5.5   11.0      W  
4      NaN    75    76    75    74    75    77   1.95    3.3    4.2      D

In [25]:
df = df.dropna(axis=0).reset_index(drop=True)
df.head()

HDays  ADays  HGDL5M  HGDL5HM  HAPL5M  HAPL5HM  AGDL5M  AGDL5AM  AAPL5M  \
0      0      0     1.0      8.0     1.4      2.0    -5.0     -4.0     0.4   
1      1      1     2.0      0.0     1.8      2.0    -2.0     -2.0     0.8   
2      0      0     4.0      5.0     2.4      2.4    -2.0     -3.0     0.8   
3      0      0     4.0      2.0     2.0      1.6    -2.0     -2.0     0.8   
4      1      1     4.0      6.0     1.8      2.0     2.0     -1.0     1.8   

   AAPL5AM  HDef  HMid  HAtt  ADef  AMid  AAtt  B365H  B365D  B365A Result  
0      0.6    75    77    78    74    75    77   1.67   3.75   5.25      L  
1      1.0    73    72    72    74    75    77   2.10   3.30   3.60      W  
2      0.8    83    82    86    74    75    77   1.20   6.50  15.00      W  
3      0.8    72    70    73    74    75    77   2.00   3.50   3.75      L  
4      1.2    79    80    79    74    75    77   1.40   4.50   8.50      W

In [26]:
df.shape

(3553, 20)

# 2. Model Building

## 2.1 Descision Tree Classifier

In [27]:
X = df.iloc[:, :-1].values
# X = df.iloc[:, :16].values
y = df.iloc[:, -1].values

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [29]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [30]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [31]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['W' 'W']
 ['W' 'W']
 ['W' 'W']
 ...
 ['W' 'W']
 ['D' 'W']
 ['W' 'W']]


In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 39  70  58]
 [ 56  80  80]
 [ 59  76 193]]


0.4388185654008439

In [36]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 5)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))

Accuracy: 44.34 %


## 2.2 SVM Classifier

In [37]:
X = df.iloc[:, :-1].values
# X = df.iloc[:, :16].values
y = df.iloc[:, -1].values

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [40]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [41]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['W' 'W']
 ['W' 'W']
 ['L' 'W']
 ...
 ['W' 'W']
 ['W' 'W']
 ['W' 'W']]


In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  3  62 135]
 [  4 141 128]
 [  4  73 339]]


0.5433070866141733

In [43]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 5)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))

Accuracy: 54.32 %
